from Source.Model.main.params.p_default import PDefaultParams
PParams = dict()

PParams['RR_PART'] = PDefaultParams.RR_PART

PParams['SEARCHING_WINDOW'] = PDefaultParams.SEARCHING_WINDOW
PParams['SHIFT_WINDOW'] = PDefaultParams.SHIFT_WINDOW

PParams['AMPLITUDE_DECREASING'] = PDefaultParams.AMPLITUDE_DECREASING
PParams['AMPLITUDE_DECREASING_POW'] = PDefaultParams.AMPLITUDE_DECREASING_POW
PParams['AMPLITUDE_DECREASING_BEGIN_PART'] = PDefaultParams.AMPLITUDE_DECREASING_BEGIN_PART
PParams['AMPLITUDE_DECREASING_LEFT_PRIVILEGE'] = PDefaultParams.AMPLITUDE_DECREASING_LEFT_PRIVILEGE
PParams['AMPLITUDE_DECREASING_RIGHT_PRIVILEGE'] = PDefaultParams.AMPLITUDE_DECREASING_RIGHT_PRIVILEGE

PParams['ONSET_CANDIDATE_COEFF'] = PDefaultParams.ONSET_CANDIDATE_COEFF
PParams['OFFSET_CANDIDATE_COEFF'] = PDefaultParams.OFFSET_CANDIDATE_COEFF
PParams['OFFSET_CANDIDATE_COEFF_OVERFLOW'] = PDefaultParams.OFFSET_CANDIDATE_COEFF_OVERFLOW

PParams['BIPHASIC_AMPLITUDE_MORE'] = PDefaultParams.BIPHASIC_AMPLITUDE_MORE
PParams['BIPHASIC_AMPLITUDE_LESS'] = PDefaultParams.BIPHASIC_AMPLITUDE_LESS

PParams['BIPHASIC_AMPLITUDE'] = PDefaultParams.BIPHASIC_AMPLITUDE

PParams['FLEXURE_SHIFT'] = PDefaultParams.FLEXURE_SHIFT
PParams['FLEXURE_AMPLITUDE'] = PDefaultParams.FLEXURE_AMPLITUDE
PParams['LITTLE_AMPLITUDE_COMP'] = PDefaultParams.LITTLE_AMPLITUDE_COMP

PParams['THRESHOLD'] = PDefaultParams.THRESHOLD

PParams['OFFSET_LOW_FLEXURE'] = PDefaultParams.OFFSET_LOW_FLEXURE

PParams['MUTABILITY_PERCENTAGE'] = PDefaultParams.MUTABILITY_PERCENTAGE

PParams['P_WDC_SCALE_ID'] = PDefaultParams.P_WDC_SCALE_ID

PParams['NUM_ZCS_FIB'] = PDefaultParams.NUM_ZCS_FIB
PParams['STD_MM_ZCS_PART_FIB'] = PDefaultParams.STD_MM_ZCS_PART_FIB

PParams['P_FLAT_ONSET_WINDOW'] = PDefaultParams.P_FLAT_ONSET_WINDOW
PParams['P_ONSET_SHARP'] = PDefaultParams.P_ONSET_SHARP

PParams['P_FLAT_OFFSET_WINDOW'] = PDefaultParams.P_FLAT_OFFSET_WINDOW
PParams['P_OFFSET_SHARP'] = PDefaultParams.P_OFFSET_SHARP

PParams['MM_WINDOW'] = PDefaultParams.MM_WINDOW

PParams['SMALL_P'] = PDefaultParams.SMALL_P



