from Source.Model.main.params.p_default import PDefaultParams
PParams = dict()

PParams['WDC_SCALE_ID'] = PDefaultParams.WDC_SCALE_ID

PParams['ALPHA_MM_WINDOW'] = PDefaultParams.ALPHA_MM_WINDOW
PParams['ALPHA_ZCS_QRS_GAP'] = PDefaultParams.ALPHA_ZCS_QRS_GAP
PParams['ALPHA_ZCS_WINDOW'] = PDefaultParams.ALPHA_ZCS_WINDOW
PParams['ALPHA_RIGHT_MM_DIST'] = PDefaultParams.ALPHA_RIGHT_MM_DIST
PParams['ALPHA_OFFSET_MM_SHARP'] = PDefaultParams.ALPHA_OFFSET_MM_SHARP
PParams['ALPHA_LEFT_MM_DIST'] = PDefaultParams.ALPHA_LEFT_MM_DIST
PParams['ALPHA_ONSET_MM_SHARP'] = PDefaultParams.ALPHA_ONSET_MM_SHARP
PParams['ALPHA_LEFT_ZC_PART_SHIFT'] = PDefaultParams.ALPHA_LEFT_ZC_PART_SHIFT
PParams['ALPHA_RIGHT_ZC_PART_SHIFT'] = PDefaultParams.ALPHA_RIGHT_ZC_PART_SHIFT
PParams['ALPHA_PEAK_SMALL_AMPL'] = PDefaultParams.ALPHA_PEAK_SMALL_AMPL
PParams['ALPHA_PEAK_BEGIN_SHIFT'] = PDefaultParams.ALPHA_PEAK_BEGIN_SHIFT
PParams['ALPHA_PEAK_ADAPT_BEGIN_PART'] = PDefaultParams.ALPHA_PEAK_ADAPT_BEGIN_PART
PParams['ALPHA_PEAK_ADAPT_POW'] = PDefaultParams.ALPHA_PEAK_ADAPT_POW
PParams['ALPHA_PEAK_ADAPT_AMPL'] = PDefaultParams.ALPHA_PEAK_ADAPT_AMPL
PParams['ALPHA_FLEX_SHIFT'] = PDefaultParams.ALPHA_FLEX_SHIFT
PParams['ALPHA_FLEX_AMPL_NGBR'] = PDefaultParams.ALPHA_FLEX_AMPL_NGBR
PParams['ALPHA_FLEX_AMPL_OLD_ZC'] = PDefaultParams.ALPHA_FLEX_AMPL_OLD_ZC
PParams['ALPHA_BIPHASE_AMPL_MORE'] = PDefaultParams.ALPHA_BIPHASE_AMPL_MORE
PParams['ALPHA_BIPHASE_AMPL_LESS'] = PDefaultParams.ALPHA_BIPHASE_AMPL_LESS
PParams['ALPHA_BIPHASE_AMPL'] = PDefaultParams.ALPHA_BIPHASE_AMPL
PParams['ALPHA_ONSET_MM'] = PDefaultParams.ALPHA_ONSET_MM
PParams['ALPHA_OFFSET_MM'] = PDefaultParams.ALPHA_OFFSET_MM
PParams['ALPHA_OFFSET_MM_OVERFLOW'] = PDefaultParams.ALPHA_OFFSET_MM_OVERFLOW
PParams['ALPHA_ONSET_OFFSET_THR'] = PDefaultParams.ALPHA_ONSET_OFFSET_THR

PParams['LEGACY_FIB_NUM_ZCS'] = PDefaultParams.LEGACY_FIB_NUM_ZCS
PParams['LEGACY_FIB_STD'] = PDefaultParams.LEGACY_FIB_STD

PParams['BETA_SCALE'] = PDefaultParams.BETA_SCALE
PParams['BETA_PEAK_ZC_AMPL'] = PDefaultParams.BETA_PEAK_ZC_AMPL


