from Source.Model.main.params.p_default import PDefaultParams
PParams = dict()

PParams['WDC_SCALE_ID'] = PDefaultParams.WDC_SCALE_ID

PParams['MM_WINDOW'] = PDefaultParams.MM_WINDOW

PParams['BEGIN_QRS_GAP_PROPORTION'] = PDefaultParams.BEGIN_QRS_GAP_PROPORTION
PParams['ZCS_SEARCHING_WINDOW'] = PDefaultParams.ZCS_SEARCHING_WINDOW

PParams['RIGHT_MM_DIST'] = PDefaultParams.RIGHT_MM_DIST
PParams['OFFSET_MM_SHARPNESS'] = PDefaultParams.OFFSET_MM_SHARPNESS

PParams['LEFT_MM_DIST'] = PDefaultParams.LEFT_MM_DIST
PParams['ONSET_MM_SHARPNESS'] = PDefaultParams.ONSET_MM_SHARPNESS

PParams['ZCS_PEAK_SEARCHING_SHIFT'] = PDefaultParams.ZCS_PEAK_SEARCHING_SHIFT

PParams['PEAK_ZC_AMPLITUDE_DECREASING_LEFT_PRIVILEGE'] = PDefaultParams.PEAK_ZC_AMPLITUDE_DECREASING_LEFT_PRIVILEGE
PParams['PEAK_ZC_AMPLITUDE_DECREASING_RIGHT_PRIVILEGE'] = PDefaultParams.PEAK_ZC_AMPLITUDE_DECREASING_RIGHT_PRIVILEGE
PParams['PEAK_ZC_AMPLITUDE_DECREASING_BEGIN_PART'] = PDefaultParams.PEAK_ZC_AMPLITUDE_DECREASING_BEGIN_PART
PParams['PEAK_ZC_AMPLITUDE_DECREASING_POW'] = PDefaultParams.PEAK_ZC_AMPLITUDE_DECREASING_POW
PParams['PEAK_ZC_AMPLITUDE_DECREASING'] = PDefaultParams.PEAK_ZC_AMPLITUDE_DECREASING

PParams['LOW_LIMIT_AMPLITUDE'] = PDefaultParams.LOW_LIMIT_AMPLITUDE

PParams['FLEXURE_SHIFT'] = PDefaultParams.FLEXURE_SHIFT
PParams['FLEXURE_AMPLITUDE_NEIGHBOUR'] = PDefaultParams.FLEXURE_AMPLITUDE_NEIGHBOUR
PParams['FLEXURE_AMPLITUDE_OLD_ZC'] = PDefaultParams.FLEXURE_AMPLITUDE_OLD_ZC

PParams['BIPHASIC_AMPLITUDE_MORE'] = PDefaultParams.BIPHASIC_AMPLITUDE_MORE
PParams['BIPHASIC_AMPLITUDE_LESS'] = PDefaultParams.BIPHASIC_AMPLITUDE_LESS
PParams['BIPHASIC_AMPLITUDE'] = PDefaultParams.BIPHASIC_AMPLITUDE

PParams['ONSET_MM_COEFF'] = PDefaultParams.ONSET_MM_COEFF

PParams['OFFSET_MM_COEFF'] = PDefaultParams.OFFSET_MM_COEFF
PParams['OFFSET_MM_COEFF_OVERFLOW'] = PDefaultParams.OFFSET_MM_COEFF_OVERFLOW

PParams['ONSET_OFFSET_THRESHOLD'] = PDefaultParams.ONSET_OFFSET_THRESHOLD

PParams['FIB_NUM_ZCS'] = PDefaultParams.FIB_NUM_ZCS
PParams['FIB_STD'] = PDefaultParams.FIB_STD

PParams['MUTABILITY_PERCENTAGE'] = PDefaultParams.MUTABILITY_PERCENTAGE





