class PDefaultParams:

    WDC_SCALE_ID = 3

    MM_WINDOW = 0.1

    BEGIN_QRS_GAP_PROPORTION = 0.45
    ZCS_SEARCHING_WINDOW = 0.3

    RIGHT_MM_DIST = 0.08
    OFFSET_MM_SHARPNESS = 3.0

    LEFT_MM_DIST = 0.08
    ONSET_MM_SHARPNESS = 5.0

    ZCS_PEAK_SEARCHING_SHIFT = 0.08

    PEAK_ZC_AMPLITUDE_DECREASING_LEFT_PRIVILEGE = 0.5
    PEAK_ZC_AMPLITUDE_DECREASING_RIGHT_PRIVILEGE = 0.2
    PEAK_ZC_AMPLITUDE_DECREASING_BEGIN_PART = 0.4
    PEAK_ZC_AMPLITUDE_DECREASING_POW = 2.0
    PEAK_ZC_AMPLITUDE_DECREASING = 0.5

    LOW_LIMIT_AMPLITUDE = 0.03

    FLEXURE_SHIFT = 0.03
    FLEXURE_AMPLITUDE_NEIGHBOUR = 0.45
    FLEXURE_AMPLITUDE_OLD_ZC = 0.35

    BIPHASIC_AMPLITUDE_MORE = 0.45
    BIPHASIC_AMPLITUDE_LESS = 2.2
    BIPHASIC_AMPLITUDE = 0.75

    ONSET_MM_COEFF = 0.4

    OFFSET_MM_COEFF = 0.4
    OFFSET_MM_COEFF_OVERFLOW = 4.0

    ONSET_OFFSET_THRESHOLD = 0.25

    FIB_NUM_ZCS = 2
    FIB_STD = 0.15

    MUTABILITY_PERCENTAGE = 0.3





