class PDefaultParams:

    WDC_SCALE_ID = 3

    ALPHA_MM_WINDOW = 0.1
    ALPHA_ZCS_QRS_GAP = 0.47
    ALPHA_ZCS_WINDOW = 0.37
    ALPHA_RIGHT_MM_DIST = 0.08
    ALPHA_OFFSET_MM_SHARP = 6.00
    ALPHA_LEFT_MM_DIST = 0.08
    ALPHA_ONSET_MM_SHARP = 6.00
    ALPHA_LEFT_ZC_PART_SHIFT = 1.0
    ALPHA_RIGHT_ZC_PART_SHIFT = 1.0
    ALPHA_PEAK_SMALL_AMPL = 0.020
    ALPHA_PEAK_BEGIN_SHIFT = 0.05
    ALPHA_PEAK_ADAPT_BEGIN_PART = 0.5
    ALPHA_PEAK_ADAPT_POW = 2.0
    ALPHA_PEAK_ADAPT_AMPL = 0.1
    ALPHA_FLEX_SHIFT = 0.030
    ALPHA_FLEX_AMPL_NGBR = 0.45
    ALPHA_FLEX_AMPL_OLD_ZC = 0.35
    ALPHA_BIPHASE_AMPL_MORE = 0.45
    ALPHA_BIPHASE_AMPL_LESS = 2.2
    ALPHA_BIPHASE_AMPL = 0.75
    ALPHA_ONSET_MM = 0.4
    ALPHA_OFFSET_MM = 0.4
    ALPHA_OFFSET_MM_OVERFLOW = 4.0
    ALPHA_ONSET_OFFSET_THR = 0.25

    LEGACY_FIB_NUM_ZCS = 4
    LEGACY_FIB_STD = 0.15





