from Source.Model.main.params.qrs_default import QRSDefaultParams

QRSParams = dict()

QRSParams['WDC_SCALE_ID'] = QRSDefaultParams.WDC_SCALE_ID
QRSParams['WDC_SCALE_ID_AUX'] = QRSDefaultParams.WDC_SCALE_ID_AUX

QRSParams['CANDIDATE_WINDOW_MIN_BEAT'] = QRSDefaultParams.CANDIDATE_WINDOW_MIN_BEAT
QRSParams['CANDIDATE_WINDOW_DELTA'] = QRSDefaultParams.CANDIDATE_WINDOW_DELTA
QRSParams['CANDIDATE_WINDOW_TRAINING_PERIOD'] = QRSDefaultParams.CANDIDATE_WINDOW_TRAINING_PERIOD
QRSParams['CANDIDATE_BEATS_COUNT_TRAINING_PERIOD'] = QRSDefaultParams.CANDIDATE_BEATS_COUNT_TRAINING_PERIOD
QRSParams['CANDIDATE_THRESHOLD_DELTA'] = QRSDefaultParams.CANDIDATE_THRESHOLD_DELTA

QRSParams['ONSET_WINDOW'] = QRSDefaultParams.ONSET_WINDOW
QRSParams['ONSET_THRESHOLD_MM'] = QRSDefaultParams.ONSET_THRESHOLD_MM
QRSParams['ONSET_AMPLITUDE_DECREASING'] = QRSDefaultParams.ONSET_AMPLITUDE_DECREASING
QRSParams['ONSET_AMPLITUDE_DECREASING_POW'] = QRSDefaultParams.ONSET_AMPLITUDE_DECREASING_POW
QRSParams['ONSET_THRESHOLD'] = QRSDefaultParams.ONSET_THRESHOLD
QRSParams['ONSET_MM_VALUE_COEFF'] = QRSDefaultParams.ONSET_MM_VALUE_COEFF
QRSParams['ONSET_MM_INDEX_SHIFT'] = QRSDefaultParams.ONSET_MM_INDEX_SHIFT
QRSParams['ONSET_COMPROMISE_WINDOW'] = QRSDefaultParams.ONSET_COMPROMISE_WINDOW
QRSParams['ONSET_COMPROMISE_MM_VALUE_COEFF'] = QRSDefaultParams.ONSET_COMPROMISE_MM_VALUE_COEFF

QRSParams['WIDE_ZC_AMPLITUDE_COEFF'] = QRSDefaultParams.WIDE_ZC_AMPLITUDE_COEFF
QRSParams['WIDE_MM_VALUE_COEFF'] = QRSDefaultParams.WIDE_MM_VALUE_COEFF

QRSParams['OFFSET_WINDOW'] = QRSDefaultParams.OFFSET_WINDOW
QRSParams['OFFSET_THRESHOLD_MM'] = QRSDefaultParams.OFFSET_THRESHOLD_MM
QRSParams['OFFSET_THRESHOLD'] = QRSDefaultParams.OFFSET_THRESHOLD

QRSParams['EXTRA_BEAT_PART'] = QRSDefaultParams.EXTRA_BEAT_PART

QRSParams['MUTABILITY_PERCENTAGE'] = QRSDefaultParams.MUTABILITY_PERCENTAGE

QRSParams['GAMMA_NORMAL_LENGTH'] = QRSDefaultParams.GAMMA_NORMAL_LENGTH
QRSParams['GAMMA_ALLOWED_DIFF_PART_LEFT'] = QRSDefaultParams.GAMMA_ALLOWED_DIFF_PART_LEFT
QRSParams['GAMMA_ALLOWED_DIFF_PART_RIGHT'] = QRSDefaultParams.GAMMA_ALLOWED_DIFF_PART_RIGHT
QRSParams['GAMMA_R_NEG_PART'] = QRSDefaultParams.GAMMA_R_NEG_PART
QRSParams['GAMMA_MM_SMALL_PART_LEFT'] = QRSDefaultParams.GAMMA_MM_SMALL_PART_LEFT
QRSParams['GAMMA_MM_SMALL_PART_RIGHT'] = QRSDefaultParams.GAMMA_MM_SMALL_PART_RIGHT
QRSParams['GAMMA_SCALES_DIFF'] = QRSDefaultParams.GAMMA_SCALES_DIFF
QRSParams['GAMMA_LEFT_ODD_XTD_ZCS_SHIFT'] = QRSDefaultParams.GAMMA_LEFT_ODD_XTD_ZCS_SHIFT
QRSParams['GAMMA_RIGHT_ODD_XTD_ZCS_SHIFT'] = QRSDefaultParams.GAMMA_RIGHT_ODD_XTD_ZCS_SHIFT
QRSParams['GAMMA_LEFT_EVEN_XTD_ZCS_SHIFT'] = QRSDefaultParams.GAMMA_LEFT_EVEN_XTD_ZCS_SHIFT
QRSParams['GAMMA_RIGHT_EVEN_XTD_ZCS_SHIFT'] = QRSDefaultParams.GAMMA_RIGHT_EVEN_XTD_ZCS_SHIFT
QRSParams['GAMMA_LEFT_XTD_ZCS_MM_PART'] = QRSDefaultParams.GAMMA_LEFT_XTD_ZCS_MM_PART
QRSParams['GAMMA_RIGHT_XTD_ZCS_MM_PART'] = QRSDefaultParams.GAMMA_RIGHT_XTD_ZCS_MM_PART
QRSParams['GAMMA_LEFT_WINDOW'] = QRSDefaultParams.GAMMA_LEFT_WINDOW
QRSParams['GAMMA_RIGHT_WINDOW'] = QRSDefaultParams.GAMMA_RIGHT_WINDOW
QRSParams['GAMMA_LEFT_Q_PART'] = QRSDefaultParams.GAMMA_LEFT_Q_PART
QRSParams['GAMMA_RIGHT_S_PART'] = QRSDefaultParams.GAMMA_RIGHT_S_PART
QRSParams['GAMMA_LEFT_ORIGIN_INCORRECT'] = QRSDefaultParams.GAMMA_LEFT_ORIGIN_INCORRECT
QRSParams['GAMMA_RIGHT_ORIGIN_INCORRECT'] = QRSDefaultParams.GAMMA_RIGHT_ORIGIN_INCORRECT
QRSParams['GAMMA_BORD_SCALE'] = QRSDefaultParams.GAMMA_BORD_SCALE
