from Source.Model.main.params.qrs_default import QRSDefaultParams

QRSParams = dict()

QRSParams['WINDOW_ZCS'] = QRSDefaultParams.WINDOW_ZCS
QRSParams['DELTA_W_CONFIRMED'] = QRSDefaultParams.DELTA_W_CONFIRMED
QRSParams['TRAINING_WINDOW'] = QRSDefaultParams.TRAINING_WINDOW
QRSParams['TRAINING_DELTAS_COUNT'] = QRSDefaultParams.TRAINING_DELTAS_COUNT
QRSParams['ONSET_WINDOW'] = QRSDefaultParams.ONSET_WINDOW
QRSParams['OFFSET_WINDOW'] = QRSDefaultParams.OFFSET_WINDOW

QRSParams['TRAINING_THRESHOLD'] = QRSDefaultParams.TRAINING_THRESHOLD

QRSParams['ONSET_THRESHOLD_MM'] = QRSDefaultParams.ONSET_THRESHOLD_MM
QRSParams['ONSET_THRESHOLD_INDEX'] = QRSDefaultParams.ONSET_THRESHOLD_INDEX

QRSParams['ONSET_AMPLITUDE_DECREASING'] = QRSDefaultParams.ONSET_AMPLITUDE_DECREASING
QRSParams['ONSET_AMPLITUDE_DECREASING_POW'] = QRSDefaultParams.ONSET_AMPLITUDE_DECREASING_POW

QRSParams['ONSET_MAX_ZC_DISTANCE'] = QRSDefaultParams.ONSET_MAX_ZC_DISTANCE
QRSParams['ONSET_MM_VALUE_PART'] = QRSDefaultParams.ONSET_MM_VALUE_PART
QRSParams['ONSET_MM_VALUE_COMP'] = QRSDefaultParams.ONSET_MM_VALUE_COMP
QRSParams['ONSET_MM_VALUE_SHIFT'] = QRSDefaultParams.ONSET_MM_VALUE_SHIFT

QRSParams['OFFSET_THRESHOLD_MM'] = QRSDefaultParams.OFFSET_THRESHOLD_MM
QRSParams['OFFSET_THRESHOLD_INDEX'] = QRSDefaultParams.OFFSET_THRESHOLD_INDEX

QRSParams['WIDE_MORPHOLOGY_AMPLITUDE'] = QRSDefaultParams.WIDE_MORPHOLOGY_AMPLITUDE
QRSParams['WIDE_MORPHOLOGY_SIDE'] = QRSDefaultParams.WIDE_MORPHOLOGY_SIDE

QRSParams['EXTRA_BEAT_PART'] = QRSDefaultParams.EXTRA_BEAT_PART

QRSParams['MUTABILITY_PERCENTAGE'] = QRSDefaultParams.MUTABILITY_PERCENTAGE

QRSParams['QRS_WDC_SCALE_ID'] = QRSDefaultParams.QRS_WDC_SCALE_ID
QRSParams['QRS_WDC_SCALE_ID_AUX'] = QRSDefaultParams.QRS_WDC_SCALE_ID_AUX
