class QRSDefaultParams:

    WINDOW_ZCS = 0.250
    DELTA_W_CONFIRMED = 0.100
    TRAINING_WINDOW = 8.0
    TRAINING_DELTAS_COUNT = 4
    ONSET_WINDOW = 0.150
    OFFSET_WINDOW = 0.150

    TRAINING_THRESHOLD = 0.45

    ONSET_THRESHOLD_MM = 0.085
    ONSET_THRESHOLD_INDEX = 0.2

    ONSET_AMPLITUDE_DECREASING = 0.4
    ONSET_AMPLITUDE_DECREASING_POW = 8

    ONSET_MAX_ZC_DISTANCE = 0.045
    ONSET_MM_VALUE_PART = 0.7
    ONSET_MM_VALUE_COMP = 0.75
    ONSET_MM_VALUE_SHIFT = 0.6

    OFFSET_THRESHOLD_MM = 0.13
    OFFSET_THRESHOLD_INDEX = 0.1

    WIDE_MORPHOLOGY_AMPLITUDE = 0.3
    WIDE_MORPHOLOGY_SIDE = 0.6

    EXTRA_BEAT_PART = 0.7

    MUTABILITY_PERCENTAGE = 0.3

    QRS_WDC_SCALE_ID = 1
    QRS_WDC_SCALE_ID_AUX = 2

