from Source.Model.main.params.t_default import TDefaultParams

TParams = dict()

TParams['WDC_SCALE_ID'] = TDefaultParams.WDC_SCALE_ID

TParams['MM_WINDOW'] = TDefaultParams.MM_WINDOW

TParams['MM_SHARPNESS'] = TDefaultParams.MM_SHARPNESS

TParams['BEGIN_SHIFT'] = TDefaultParams.BEGIN_SHIFT
TParams['END_QRS_GAP_PROPORTION'] = TDefaultParams.END_QRS_GAP_PROPORTION

TParams['PEAK_ZC_AMPLITUDE_DECREASING_LEFT_PRIVILEGE'] = TDefaultParams.PEAK_ZC_AMPLITUDE_DECREASING_LEFT_PRIVILEGE
TParams['PEAK_ZC_AMPLITUDE_DECREASING_RIGHT_PRIVILEGE'] = TDefaultParams.PEAK_ZC_AMPLITUDE_DECREASING_RIGHT_PRIVILEGE
TParams['PEAK_ZC_AMPLITUDE_DECREASING_BEGIN_PART'] = TDefaultParams.PEAK_ZC_AMPLITUDE_DECREASING_BEGIN_PART
TParams['PEAK_ZC_AMPLITUDE_DECREASING_POW'] = TDefaultParams.PEAK_ZC_AMPLITUDE_DECREASING_POW
TParams['PEAK_ZC_AMPLITUDE_DECREASING'] = TDefaultParams.PEAK_ZC_AMPLITUDE_DECREASING

TParams['FLEXURE_SHIFT'] = TDefaultParams.FLEXURE_SHIFT
TParams['FLEXURE_AMPLITUDE_NEIGHBOUR'] = TDefaultParams.FLEXURE_AMPLITUDE_NEIGHBOUR
TParams['FLEXURE_AMPLITUDE_OLD_ZC'] = TDefaultParams.FLEXURE_AMPLITUDE_OLD_ZC
TParams['FLEXURE_BEGIN_PART'] = TDefaultParams.FLEXURE_BEGIN_PART
TParams['FLEXURE_END_PART'] = TDefaultParams.FLEXURE_END_PART

TParams['BIPHASIC_AMPLITUDE_LEFT'] = TDefaultParams.BIPHASIC_AMPLITUDE_LEFT
TParams['BIPHASIC_AMPLITUDE_RIGHT'] = TDefaultParams.BIPHASIC_AMPLITUDE_RIGHT
TParams['BIPHASIC_LIMIT_SHIFT'] = TDefaultParams.BIPHASIC_LIMIT_SHIFT

TParams['ONSET_OFFSET_THRESHOLD_MM'] = TDefaultParams.ONSET_OFFSET_THRESHOLD_MM

TParams['MUTABILITY_PERCENTAGE'] = TDefaultParams.MUTABILITY_PERCENTAGE








