from Source.Model.main.params.t_default import TDefaultParams

TParams = dict()

TParams['WDC_SCALE_ID'] = TDefaultParams.WDC_SCALE_ID

TParams['ALPHA_MM_WINDOW'] = TDefaultParams.ALPHA_MM_WINDOW
TParams['ALPHA_BEGIN_SHIFT'] = TDefaultParams.ALPHA_BEGIN_SHIFT
TParams['ALPHA_QRS_BTW'] = TDefaultParams.ALPHA_QRS_BTW
TParams['ALPHA_QRS_GAP'] = TDefaultParams.ALPHA_QRS_GAP
TParams['ALPHA_MM_SHARP'] = TDefaultParams.ALPHA_MM_SHARP
TParams['ALPHA_PEAK_ZC_AMPL_DEC_LEFT'] = TDefaultParams.ALPHA_PEAK_ZC_AMPL_DEC_LEFT
TParams['ALPHA_PEAK_ZC_AMPL_DEC_RIGHT'] = TDefaultParams.ALPHA_PEAK_ZC_AMPL_DEC_RIGHT
TParams['ALPHA_PEAK_ZC_AMPL_DEC_BEGIN'] = TDefaultParams.ALPHA_PEAK_ZC_AMPL_DEC_BEGIN
TParams['ALPHA_PEAK_ZC_AMPL_DEC_POW'] = TDefaultParams.ALPHA_PEAK_ZC_AMPL_DEC_POW
TParams['ALPHA_PEAK_ZC_AMPL_DEC_COEFF'] = TDefaultParams.ALPHA_PEAK_ZC_AMPL_DEC_COEFF
TParams['ALPHA_FLEX_SHIFT'] = TDefaultParams.ALPHA_FLEX_SHIFT
TParams['ALPHA_FLEX_AMPL_NGBR'] = TDefaultParams.ALPHA_FLEX_AMPL_NGBR
TParams['ALPHA_FLEX_AMPL_OLD_ZC'] = TDefaultParams.ALPHA_FLEX_AMPL_OLD_ZC
TParams['ALPHA_FLEX_BEGIN_PART'] = TDefaultParams.ALPHA_FLEX_BEGIN_PART
TParams['ALPHA_FLEX_END_PART'] = TDefaultParams.ALPHA_FLEX_END_PART
TParams['ALPHA_BIPHASE_AMPL_LEFT'] = TDefaultParams.ALPHA_BIPHASE_AMPL_LEFT
TParams['ALPHA_BIPHASE_AMPL_RIGHT'] = TDefaultParams.ALPHA_BIPHASE_AMPL_RIGHT
TParams['ALPHA_BIPHASE_AMPL_SHIFT'] = TDefaultParams.ALPHA_BIPHASE_AMPL_SHIFT
TParams['ALPHA_ONSET_OFFSET_MM'] = TDefaultParams.ALPHA_ONSET_OFFSET_MM

TParams['BETA_SCALE'] = TDefaultParams.BETA_SCALE
TParams['BETA_PEAK_ZC_AMPL'] = TDefaultParams.BETA_PEAK_ZC_AMPL

TParams['MUTABILITY_PERCENTAGE'] = TDefaultParams.MUTABILITY_PERCENTAGE








