class TDefaultParams:

    WDC_SCALE_ID = 4

    ALPHA_MM_WINDOW = 0.15
    ALPHA_BEGIN_SHIFT = 0.05
    ALPHA_QRS_GAP = 0.5
    ALPHA_MM_SHARP = 5.0
    ALPHA_PEAK_ZC_AMPL_DEC_LEFT = 0.6
    ALPHA_PEAK_ZC_AMPL_DEC_RIGHT = 0.6

    ALPHA_PEAK_ZC_AMPL_DEC_BEGIN = 0.5
    ALPHA_PEAK_ZC_AMPL_DEC_POW = 4.0
    ALPHA_PEAK_ZC_AMPL_DEC_COEFF = 0.5

    FLEXURE_SHIFT = 0.03
    FLEXURE_AMPLITUDE_NEIGHBOUR = 0.5
    FLEXURE_AMPLITUDE_OLD_ZC = 0.3
    FLEXURE_BEGIN_PART = 0.15
    FLEXURE_END_PART = 0.6

    BIPHASIC_AMPLITUDE_LEFT = 0.890625
    BIPHASIC_AMPLITUDE_RIGHT = 0.703125
    BIPHASIC_LIMIT_SHIFT = 0.13

    ONSET_OFFSET_THRESHOLD_MM = 0.140625

    MUTABILITY_PERCENTAGE = 0.3


